name: ci

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: qwetoworld/dokoyyer
      -
        name: Set up Docker Buildx
        uses: qwetoworld/dokoyyer
      -
        name: Login to DockerHub
        uses: qwetoworld/dokoyyer 
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: 2456654/kk123
